// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUp6yjLo0hYZhOa1ChRFt2XzBgw62WAIE',
    appId: '1:853240139602:web:6118f9b93a78cf81e3348b',
    messagingSenderId: '853240139602',
    projectId: 'mobile-crud-daniel',
    authDomain: 'mobile-crud-daniel.firebaseapp.com',
    storageBucket: 'mobile-crud-daniel.firebasestorage.app',
    measurementId: 'G-XGF3977P10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrUSD7MFL9GiQ-R_3zA4F9MXlZl6J4Do',
    appId: '1:853240139602:android:5310c7a167c0b123e3348b',
    messagingSenderId: '853240139602',
    projectId: 'mobile-crud-daniel',
    storageBucket: 'mobile-crud-daniel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRE07eJwRSQk9JHLMkmegJdIrAbN1eSk4',
    appId: '1:853240139602:ios:7d8d77283a7d9db0e3348b',
    messagingSenderId: '853240139602',
    projectId: 'mobile-crud-daniel',
    storageBucket: 'mobile-crud-daniel.firebasestorage.app',
    iosBundleId: 'com.example.crudCloudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRE07eJwRSQk9JHLMkmegJdIrAbN1eSk4',
    appId: '1:853240139602:ios:7d8d77283a7d9db0e3348b',
    messagingSenderId: '853240139602',
    projectId: 'mobile-crud-daniel',
    storageBucket: 'mobile-crud-daniel.firebasestorage.app',
    iosBundleId: 'com.example.crudCloudFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUp6yjLo0hYZhOa1ChRFt2XzBgw62WAIE',
    appId: '1:853240139602:web:edd7d72639259a49e3348b',
    messagingSenderId: '853240139602',
    projectId: 'mobile-crud-daniel',
    authDomain: 'mobile-crud-daniel.firebaseapp.com',
    storageBucket: 'mobile-crud-daniel.firebasestorage.app',
    measurementId: 'G-9GQY9W7CJN',
  );
}
